In [ ]:
!pip install nltk
!pip install scikit-learn

In [ ]:
  import pandas as pd
  import numpy as np
  import re
  import nltk
  from nltk.corpus import stopwords
  from nltk import ngrams
  from nltk import word_tokenize
  import string
  from sklearn import metrics
  from nltk.stem import PorterStemmer
  nltk.download('punkt')  # Ensure punkt is downloaded
  nltk.download('stopwords')  # Ensure stopwords are downloaded
  from nltk.corpus import stopwords
  from nltk.tokenize import word_tokenize
  nltk.download('punkt_tab')# used for tokenization

In [14]:
df = pd.read_csv("ISEAR_dataset.csv",header=None)

In [16]:
df.head(5)

           0                                                  1    2
0  sentiment                                            content  NaN
1        joy  On days when I feel close to my partner and ot...  NaN
2       fear  Every time I imagine that someone I love or I ...  NaN
3      anger  When I had been obviously unjustly treated and...  NaN
4    sadness  When I think about the short time that we live...  NaN

In [17]:
df.tail()

          0                                                  1    2
7512  shame  Two years back someone invited me to be the tu...  NaN
7513  shame  I had taken the responsibility to do something...  NaN
7514   fear  I was at home and I heard a loud sound of spit...  NaN
7515  guilt  I did not do the homework that the teacher had...  NaN
7516   fear  I had shouted at my younger brother and he was...  NaN

In [19]:
print(df.columns)

Index([0, 1, 2], dtype='int64')

In [20]:


# Count the number of sentences per emotion category
emotion_counts = df[0].value_counts()

# Print the emotion categories and their sentence counts
print("Emotion Categories and Number of Sentences:")
print(emotion_counts)

Emotion Categories and Number of Sentences:
0
joy          1092
sadness      1082
anger        1079
fear         1076
shame        1071
disgust      1066
guilt        1049
sentiment       1
guit            1
Name: count, dtype: int64

In [21]:
col = [0,1]
new_df = df[col]
new_df = new_df[pd.notnull(df[1])]
new_df.columns = ['Emotion','Text']
new_df.head()

     Emotion                                               Text
0  sentiment                                            content
1        joy  On days when I feel close to my partner and ot...
2       fear  Every time I imagine that someone I love or I ...
3      anger  When I had been obviously unjustly treated and...
4    sadness  When I think about the short time that we live...

In [22]:
def preprocess_text(text):
    text = text.lower()
    text = re.sub(r'[^a-z\s]', '', text)  # Keep letters and spaces
    return text  # Do not remove stopwords or pronouns
new_df['processed_text'] = new_df['Text'].apply(preprocess_text)

In [23]:
print(new_df)

        Emotion                                               Text  \
0     sentiment                                            content
1           joy  On days when I feel close to my partner and ot...
2          fear  Every time I imagine that someone I love or I ...
3         anger  When I had been obviously unjustly treated and...
4       sadness  When I think about the short time that we live...
...         ...                                                ...
7512      shame  Two years back someone invited me to be the tu...
7513      shame  I had taken the responsibility to do something...
7514       fear  I was at home and I heard a loud sound of spit...
7515      guilt  I did not do the homework that the teacher had...
7516       fear  I had shouted at my younger brother and he was...

                                         processed_text
0                                               content
1     on days when i feel close to my partner and ot...
2     every time i imagine that someone i love or i ...
3     when i had been obviously unjustly treated and...
4     when i think about the short time that we live...
...                                                 ...
7512  two years back someone invited me to be the tu...
7513  i had taken the responsibility to do something...
7514  i was at home and i heard a loud sound of spit...
7515  i did not do the homework that the teacher had...
7516  i had shouted at my younger brother and he was...

[7517 rows x 3 columns]

In [24]:
new_df.columns

Index(['Emotion', 'Text', 'processed_text'], dtype='object')

In [25]:
display(new_df)

,Emotion,Text,processed_text
0,sentiment,content,content
1,joy,On days when I feel close to my partner and ot...,on days when i feel close to my partner and ot...
2,fear,Every time I imagine that someone I love or I ...,every time i imagine that someone i love or i ...
3,anger,When I had been obviously unjustly treated and...,when i had been obviously unjustly treated and...
4,sadness,When I think about the short time that we live...,when i think about the short time that we live...
...,...,...,...
7512,shame,Two years back someone invited me to be the tu...,two years back someone invited me to be the tu...
7513,shame,I had taken the responsibility to do something...,i had taken the responsibility to do something...
7514,fear,I was at home and I heard a loud sound of spit...,i was at home and i heard a loud sound of spit...
7515,guilt,I did not do the homework that the teacher had...,i did not do the homework that the teacher had...
7516,fear,I had shouted at my younger brother and he was...,i had shouted at my younger brother and he was...

In [26]:
from IPython.display import display
display(new_df[['Text', 'processed_text']].head(10))

,Text,processed_text
0,content,content
1,On days when I feel close to my partner and ot...,on days when i feel close to my partner and ot...
2,Every time I imagine that someone I love or I ...,every time i imagine that someone i love or i ...
3,When I had been obviously unjustly treated and...,when i had been obviously unjustly treated and...
4,When I think about the short time that we live...,when i think about the short time that we live...
5,At a gathering I found myself involuntarily si...,at a gathering i found myself involuntarily si...
6,When I realized that I was directing the feeli...,when i realized that i was directing the feeli...
7,I feel guilty when when I realize that I consi...,i feel guilty when when i realize that i consi...
8,After my girlfriend had taken her exam we went...,after my girlfriend had taken her exam we went...
9,"When, for the first time I realized the meanin...",when for the first time i realized the meaning...

In [34]:
!python.exe -m pip install --upgrade pip

Requirement already satisfied: pip in c:\users\angel\appdata\local\programs\python\python313\lib\site-packages (25.3)
Collecting pip
  Downloading pip-26.0.1-py3-none-any.whl.metadata (4.7 kB)
Downloading pip-26.0.1-py3-none-any.whl (1.8 MB)
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----------------------------------- ---- 1.6/1.8 MB 6.0 MB/s eta 0:00:01
   ---------------------------------------- 1.8/1.8 MB 5.3 MB/s  0:00:00
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 25.3
    Uninstalling pip-25.3:
      Successfully uninstalled pip-25.3
Successfully installed pip-26.0.1

In [35]:
!pip install transformers torch numpy

Requirement already satisfied: transformers in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (5.3.0)
Requirement already satisfied: torch in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (2.10.0)
Requirement already satisfied: numpy in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (2.2.3)
Requirement already satisfied: huggingface-hub<2.0,>=1.3.0 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from transformers) (1.7.1)
Requirement already satisfied: packaging>=20.0 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from transformers) (24.2)
Requirement already satisfied: pyyaml>=5.1 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from transformers) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from transformers) (2026.2.28)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from transformers) (0.22.2)
Requirement already satisfied: typer in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from transformers) (0.24.1)
Requirement already satisfied: safetensors>=0.4.3 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from transformers) (4.67.3)
Requirement already satisfied: filelock>=3.10.0 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (3.25.2)
Requirement already satisfied: fsspec>=2023.5.0 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (2025.9.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.2 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (1.4.2)
Requirement already satisfied: httpx<1,>=0.23.0 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (4.15.0)
Requirement already satisfied: anyio in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (4.8.0)
Requirement already satisfied: certifi in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (2024.12.14)
Requirement already satisfied: httpcore==1.* in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (1.0.7)
Requirement already satisfied: idna in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (3.10)
Requirement already satisfied: h11<0.15,>=0.13 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (0.14.0)
Requirement already satisfied: sympy>=1.13.3 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from torch) (3.6.1)
Requirement already satisfied: jinja2 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from torch) (3.1.5)
Requirement already satisfied: setuptools in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from torch) (75.7.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: colorama in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from tqdm>=4.27->transformers) (0.4.6)
Requirement already satisfied: sniffio>=1.1 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from anyio->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (1.3.1)
Requirement already satisfied: MarkupSafe>=2.0 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from jinja2->torch) (3.0.2)
Requirement already satisfied: click>=8.2.1 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from typer->transformers) (8.2.1)
Requirement already satisfied: shellingham>=1.3.0 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from typer->transformers) (14.3.3)
Requirement already satisfied: annotated-doc>=0.0.2 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from typer->transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from rich>=12.3.0->typer->transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from rich>=12.3.0->typer->transformers) (2.19.1)
Requirement already satisfied: mdurl~=0.1 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->transformers) (0.1.2)

In [36]:
import torch
from transformers import BertTokenizer, BertModel

# Load BERT tokenizer and model
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = BertModel.from_pretrained('bert-base-uncased')

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertModel LOAD REPORT from: bert-base-uncased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [37]:
import torch
from transformers import BertTokenizer, BertModel

# Load BERT tokenizer and model
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
bert_model = BertModel.from_pretrained('bert-base-uncased') # Changed 'model' to 'bert_model'

def get_bert_embeddings(text):
    # Tokenize input text and convert to tensor
    inputs = tokenizer(text, return_tensors="pt", padding=True, truncation=True, max_length=512)

    # Get BERT embeddings
    with torch.no_grad():
        outputs = bert_model(**inputs) # Use 'bert_model' instead of 'model'

    # Extract the embeddings (CLS token or mean of token embeddings)
    cls_embedding = outputs.last_hidden_state[:, 0, :].squeeze().numpy()  # CLS token embedding
    return cls_embedding

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertModel LOAD REPORT from: bert-base-uncased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [39]:
import numpy as np

# Apply the function to get embeddings for each text entry
new_df['bert_embedding'] = new_df['processed_text'].apply(lambda x: get_bert_embeddings(x))

# Convert embeddings to a NumPy array for easier manipulation
bert_embeddings = np.stack(new_df['bert_embedding'].values)

In [40]:
new_df[['processed_text', 'bert_embedding']].head()

,processed_text,bert_embedding
0,content,"[-0.15086891, 0.20300996, 0.12541631, -0.28433..."
1,on days when i feel close to my partner and ot...,"[0.0035294862, 0.14541647, -0.42638662, -0.569..."
2,every time i imagine that someone i love or i ...,"[0.14522912, 0.36880115, 0.050217673, -0.41835..."
3,when i had been obviously unjustly treated and...,"[-0.12886678, -0.18776208, -0.3655169, -0.0701..."
4,when i think about the short time that we live...,"[-0.047033098, 0.09166224, -0.521177, -0.57109..."

In [42]:
!pip install tensorflow

Collecting tensorflow
  Downloading tensorflow-2.21.0-cp313-cp313-win_amd64.whl.metadata (4.5 kB)
Collecting absl-py>=1.0.0 (from tensorflow)
  Downloading absl_py-2.4.0-py3-none-any.whl.metadata (3.3 kB)
Collecting astunparse>=1.6.0 (from tensorflow)
  Downloading astunparse-1.6.3-py2.py3-none-any.whl.metadata (4.4 kB)
Collecting flatbuffers>=25.9.23 (from tensorflow)
  Downloading flatbuffers-25.12.19-py2.py3-none-any.whl.metadata (1.0 kB)
Collecting gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 (from tensorflow)
  Downloading gast-0.7.0-py3-none-any.whl.metadata (1.5 kB)
Collecting google_pasta>=0.1.1 (from tensorflow)
  Downloading google_pasta-0.2.0-py3-none-any.whl.metadata (814 bytes)
Collecting libclang>=13.0.0 (from tensorflow)
  Downloading libclang-18.1.1-py2.py3-none-win_amd64.whl.metadata (5.3 kB)
Collecting opt_einsum>=2.3.2 (from tensorflow)
  Downloading opt_einsum-3.4.0-py3-none-any.whl.metadata (6.3 kB)
Requirement already satisfied: packaging in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from tensorflow) (24.2)
Collecting protobuf<8.0.0,>=6.31.1 (from tensorflow)
  Downloading protobuf-7.34.0-cp310-abi3-win_amd64.whl.metadata (595 bytes)
Requirement already satisfied: requests<3,>=2.21.0 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from tensorflow) (2.32.3)
Requirement already satisfied: setuptools in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from tensorflow) (75.7.0)
Requirement already satisfied: six>=1.12.0 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from tensorflow) (1.17.0)
Collecting termcolor>=1.1.0 (from tensorflow)
  Downloading termcolor-3.3.0-py3-none-any.whl.metadata (6.5 kB)
Requirement already satisfied: typing_extensions>=3.6.6 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from tensorflow) (4.15.0)
Collecting wrapt>=1.11.0 (from tensorflow)
  Downloading wrapt-2.1.2-cp313-cp313-win_amd64.whl.metadata (7.6 kB)
Collecting grpcio<2.0,>=1.24.3 (from tensorflow)
  Downloading grpcio-1.78.0-cp313-cp313-win_amd64.whl.metadata (3.9 kB)
Collecting keras>=3.12.0 (from tensorflow)
  Downloading keras-3.13.2-py3-none-any.whl.metadata (6.3 kB)
Requirement already satisfied: numpy>=1.26.0 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from tensorflow) (2.2.3)
Collecting h5py<3.15.0,>=3.11.0 (from tensorflow)
  Downloading h5py-3.14.0-cp313-cp313-win_amd64.whl.metadata (2.7 kB)
Collecting ml_dtypes<1.0.0,>=0.5.1 (from tensorflow)
  Downloading ml_dtypes-0.5.4-cp313-cp313-win_amd64.whl.metadata (9.2 kB)
Requirement already satisfied: charset-normalizer<4,>=2 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2024.12.14)
Collecting wheel<1.0,>=0.23.0 (from astunparse>=1.6.0->tensorflow)
  Downloading wheel-0.46.3-py3-none-any.whl.metadata (2.4 kB)
Requirement already satisfied: rich in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from keras>=3.12.0->tensorflow) (14.3.3)
Collecting namex (from keras>=3.12.0->tensorflow)
  Downloading namex-0.1.0-py3-none-any.whl.metadata (322 bytes)
Collecting optree (from keras>=3.12.0->tensorflow)
  Downloading optree-0.19.0-cp313-cp313-win_amd64.whl.metadata (35 kB)
Requirement already satisfied: markdown-it-py>=2.2.0 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from rich->keras>=3.12.0->tensorflow) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from rich->keras>=3.12.0->tensorflow) (2.19.1)
Requirement already satisfied: mdurl~=0.1 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.12.0->tensorflow) (0.1.2)
Downloading tensorflow-2.21.0-cp313-cp313-win_amd64.whl (351.2 MB)
   ---------------------------------------- 0.0/351.2 MB ? eta -:--:--
   ---------------------------------------- 1.3/351.2 MB 6.0 MB/s eta 0:00:58
   ---------------------------------------- 2.6/351.2 MB 6.4 MB/s eta 0:00:55
   ---------------------------------------- 3.9/351.2 MB 6.5 MB/s eta 0:00:54
    --------------------------------------- 5.2/351.2 MB 6.4 MB/s eta 0:00:54
    --------------------------------------- 6.6/351.2 MB 6.3 MB/s eta 0:00:55
    --------------------------------------- 7.9/351.2 MB 6.3 MB/s eta 0:00:55
   - -------------------------------------- 9.2/351.2 MB 6.4 MB/s eta 0:00:54
   - -------------------------------------- 10.7/351.2 MB 6.4 MB/s eta 0:00:53
   - -------------------------------------- 12.1/351.2 MB 6.5 MB/s eta 0:00:53
   - -------------------------------------- 13.6/351.2 MB 6.6 MB/s eta 0:00:52
   - -------------------------------------- 14.9/351.2 MB 6.6 MB/s eta 0:00:52
   - -------------------------------------- 16.3/351.2 MB 6.6 MB/s eta 0:00:51
   -- ------------------------------------- 17.8/351.2 MB 6.6 MB/s eta 0:00:51
   -- ------------------------------------- 19.1/351.2 MB 6.6 MB/s eta 0:00:51
   -- ------------------------------------- 20.4/351.2 MB 6.6 MB/s eta 0:00:50
   -- ------------------------------------- 21.8/351.2 MB 6.6 MB/s eta 0:00:50
   -- ------------------------------------- 23.3/351.2 MB 6.7 MB/s eta 0:00:50
   -- ------------------------------------- 24.6/351.2 MB 6.6 MB/s eta 0:00:50
   -- ------------------------------------- 26.2/351.2 MB 6.7 MB/s eta 0:00:49
   --- ------------------------------------ 27.5/351.2 MB 6.7 MB/s eta 0:00:49
   --- ------------------------------------ 28.8/351.2 MB 6.7 MB/s eta 0:00:49
   --- ------------------------------------ 30.4/351.2 MB 6.7 MB/s eta 0:00:49
   --- ------------------------------------ 31.7/351.2 MB 6.7 MB/s eta 0:00:48
   --- ------------------------------------ 33.3/351.2 MB 6.7 MB/s eta 0:00:48
   --- ------------------------------------ 34.6/351.2 MB 6.7 MB/s eta 0:00:48
   ---- ----------------------------------- 35.9/351.2 MB 6.7 MB/s eta 0:00:48
   ---- ----------------------------------- 37.2/351.2 MB 6.7 MB/s eta 0:00:48
   ---- ----------------------------------- 38.5/351.2 MB 6.6 MB/s eta 0:00:48
   ---- ----------------------------------- 39.8/351.2 MB 6.7 MB/s eta 0:00:47
   ---- ----------------------------------- 41.4/351.2 MB 6.7 MB/s eta 0:00:47
   ---- ----------------------------------- 42.7/351.2 MB 6.7 MB/s eta 0:00:47
   ----- ---------------------------------- 44.3/351.2 MB 6.7 MB/s eta 0:00:47
   ----- ---------------------------------- 45.6/351.2 MB 6.7 MB/s eta 0:00:46
   ----- ---------------------------------- 46.9/351.2 MB 6.7 MB/s eta 0:00:46
   ----- ---------------------------------- 48.2/351.2 MB 6.7 MB/s eta 0:00:46
   ----- ---------------------------------- 49.8/351.2 MB 6.7 MB/s eta 0:00:46
   ----- ---------------------------------- 51.1/351.2 MB 6.7 MB/s eta 0:00:46
   ------ --------------------------------- 52.7/351.2 MB 6.7 MB/s eta 0:00:45
   ------ --------------------------------- 54.0/351.2 MB 6.7 MB/s eta 0:00:45
   ------ --------------------------------- 55.6/351.2 MB 6.7 MB/s eta 0:00:45
   ------ --------------------------------- 56.9/351.2 MB 6.7 MB/s eta 0:00:45
   ------ --------------------------------- 58.2/351.2 MB 6.7 MB/s eta 0:00:44
   ------ --------------------------------- 59.8/351.2 MB 6.7 MB/s eta 0:00:44
   ------ --------------------------------- 60.8/351.2 MB 6.7 MB/s eta 0:00:44
   ------- -------------------------------- 62.1/351.2 MB 6.7 MB/s eta 0:00:44
   ------- -------------------------------- 63.7/351.2 MB 6.6 MB/s eta 0:00:44
   ------- -------------------------------- 65.3/351.2 MB 6.7 MB/s eta 0:00:43
   ------- -------------------------------- 66.6/351.2 MB 6.7 MB/s eta 0:00:43
   ------- -------------------------------- 68.2/351.2 MB 6.7 MB/s eta 0:00:43
   ------- -------------------------------- 69.5/351.2 MB 6.7 MB/s eta 0:00:43
   -------- ------------------------------- 71.0/351.2 MB 6.7 MB/s eta 0:00:43
   -------- ------------------------------- 72.4/351.2 MB 6.7 MB/s eta 0:00:42
   -------- ------------------------------- 73.7/351.2 MB 6.7 MB/s eta 0:00:42
   -------- ------------------------------- 75.2/351.2 MB 6.7 MB/s eta 0:00:42
   -------- ------------------------------- 76.5/351.2 MB 6.7 MB/s eta 0:00:42
   -------- ------------------------------- 78.1/351.2 MB 6.7 MB/s eta 0:00:41
   --------- ------------------------------ 79.4/351.2 MB 6.7 MB/s eta 0:00:41
   --------- ------------------------------ 81.0/351.2 MB 6.7 MB/s eta 0:00:41
   --------- ------------------------------ 82.3/351.2 MB 6.7 MB/s eta 0:00:41
   --------- ------------------------------ 83.9/351.2 MB 6.7 MB/s eta 0:00:40
   --------- ------------------------------ 85.2/351.2 MB 6.7 MB/s eta 0:00:40
   --------- ------------------------------ 86.5/351.2 MB 6.7 MB/s eta 0:00:40
   ---------- ----------------------------- 88.1/351.2 MB 6.7 MB/s eta 0:00:40
   ---------- ----------------------------- 89.4/351.2 MB 6.7 MB/s eta 0:00:40
   ---------- ----------------------------- 91.0/351.2 MB 6.7 MB/s eta 0:00:39
   ---------- ----------------------------- 92.3/351.2 MB 6.7 MB/s eta 0:00:39
   ---------- ----------------------------- 93.6/351.2 MB 6.7 MB/s eta 0:00:39
   ---------- ----------------------------- 95.2/351.2 MB 6.7 MB/s eta 0:00:39
   ---------- ----------------------------- 96.5/351.2 MB 6.7 MB/s eta 0:00:38
   ----------- ---------------------------- 98.0/351.2 MB 6.7 MB/s eta 0:00:38
   ----------- ---------------------------- 99.4/351.2 MB 6.7 MB/s eta 0:00:38
   ----------- ---------------------------- 100.9/351.2 MB 6.7 MB/s eta 0:00:38
   ----------- ---------------------------- 102.2/351.2 MB 6.7 MB/s eta 0:00:38
   ----------- ---------------------------- 103.8/351.2 MB 6.7 MB/s eta 0:00:37
   ----------- ---------------------------- 105.1/351.2 MB 6.7 MB/s eta 0:00:37
   ------------ --------------------------- 106.7/351.2 MB 6.7 MB/s eta 0:00:37
   ------------ --------------------------- 108.0/351.2 MB 6.7 MB/s eta 0:00:37
   ------------ --------------------------- 109.6/351.2 MB 6.7 MB/s eta 0:00:36
   ------------ --------------------------- 110.9/351.2 MB 6.7 MB/s eta 0:00:36
   ------------ --------------------------- 112.5/351.2 MB 6.7 MB/s eta 0:00:36
   ------------ --------------------------- 113.8/351.2 MB 6.7 MB/s eta 0:00:36
   ------------- -------------------------- 115.1/351.2 MB 6.7 MB/s eta 0:00:36
   ------------- -------------------------- 116.7/351.2 MB 6.7 MB/s eta 0:00:35
   ------------- -------------------------- 118.0/351.2 MB 6.7 MB/s eta 0:00:35
   ------------- -------------------------- 119.3/351.2 MB 6.7 MB/s eta 0:00:35
   ------------- -------------------------- 120.8/351.2 MB 6.7 MB/s eta 0:00:35
   ------------- -------------------------- 122.4/351.2 MB 6.7 MB/s eta 0:00:34
   -------------- ------------------------- 124.0/351.2 MB 6.7 MB/s eta 0:00:34
   -------------- ------------------------- 125.3/351.2 MB 6.7 MB/s eta 0:00:34
   -------------- ------------------------- 126.9/351.2 MB 6.8 MB/s eta 0:00:34
   -------------- ------------------------- 128.2/351.2 MB 6.8 MB/s eta 0:00:34
   -------------- ------------------------- 129.8/351.2 MB 6.8 MB/s eta 0:00:33
   -------------- ------------------------- 131.1/351.2 MB 6.8 MB/s eta 0:00:33
   --------------- ------------------------ 132.4/351.2 MB 6.8 MB/s eta 0:00:33
   --------------- ------------------------ 133.7/351.2 MB 6.7 MB/s eta 0:00:33
   --------------- ------------------------ 135.3/351.2 MB 6.7 MB/s eta 0:00:33
   --------------- ------------------------ 136.6/351.2 MB 6.7 MB/s eta 0:00:32
   --------------- ------------------------ 137.9/351.2 MB 6.7 MB/s eta 0:00:32
   --------------- ------------------------ 139.5/351.2 MB 6.7 MB/s eta 0:00:32
   ---------------- ----------------------- 140.8/351.2 MB 6.7 MB/s eta 0:00:32
   ---------------- ----------------------- 142.1/351.2 MB 6.7 MB/s eta 0:00:32
   ---------------- ----------------------- 143.4/351.2 MB 6.7 MB/s eta 0:00:31
   ---------------- ----------------------- 144.7/351.2 MB 6.7 MB/s eta 0:00:31
   ---------------- ----------------------- 146.0/351.2 MB 6.7 MB/s eta 0:00:31
   ---------------- ----------------------- 147.6/351.2 MB 6.7 MB/s eta 0:00:31
   ---------------- ----------------------- 148.9/351.2 MB 6.7 MB/s eta 0:00:31
   ----------------- ---------------------- 150.5/351.2 MB 6.7 MB/s eta 0:00:30
   ----------------- ---------------------- 151.5/351.2 MB 6.7 MB/s eta 0:00:30
   ----------------- ---------------------- 153.1/351.2 MB 6.7 MB/s eta 0:00:30
   ----------------- ---------------------- 154.4/351.2 MB 6.7 MB/s eta 0:00:30
   ----------------- ---------------------- 155.7/351.2 MB 6.7 MB/s eta 0:00:30
   ----------------- ---------------------- 157.0/351.2 MB 6.7 MB/s eta 0:00:29
   ------------------ --------------------- 158.3/351.2 MB 6.7 MB/s eta 0:00:29
   ------------------ --------------------- 159.9/351.2 MB 6.7 MB/s eta 0:00:29
   ------------------ --------------------- 161.5/351.2 MB 6.7 MB/s eta 0:00:29
   ------------------ --------------------- 162.8/351.2 MB 6.7 MB/s eta 0:00:29
   ------------------ --------------------- 164.4/351.2 MB 6.7 MB/s eta 0:00:28
   ------------------ --------------------- 165.7/351.2 MB 6.7 MB/s eta 0:00:28
   ------------------- -------------------- 167.0/351.2 MB 6.7 MB/s eta 0:00:28
   ------------------- -------------------- 168.6/351.2 MB 6.7 MB/s eta 0:00:28
   ------------------- -------------------- 169.9/351.2 MB 6.7 MB/s eta 0:00:27
   ------------------- -------------------- 171.4/351.2 MB 6.7 MB/s eta 0:00:27
   ------------------- -------------------- 172.8/351.2 MB 6.7 MB/s eta 0:00:27
   ------------------- -------------------- 174.1/351.2 MB 6.7 MB/s eta 0:00:27
   -------------------- ------------------- 175.6/351.2 MB 6.7 MB/s eta 0:00:27
   -------------------- ------------------- 176.9/351.2 MB 6.7 MB/s eta 0:00:26
   -------------------- ------------------- 178.5/351.2 MB 6.7 MB/s eta 0:00:26
   -------------------- ------------------- 179.8/351.2 MB 6.7 MB/s eta 0:00:26
   -------------------- ------------------- 181.4/351.2 MB 6.7 MB/s eta 0:00:26
   -------------------- ------------------- 182.7/351.2 MB 6.7 MB/s eta 0:00:26
   -------------------- ------------------- 184.0/351.2 MB 6.7 MB/s eta 0:00:25
   --------------------- ------------------ 185.6/351.2 MB 6.7 MB/s eta 0:00:25
   --------------------- ------------------ 186.9/351.2 MB 6.7 MB/s eta 0:00:25
   --------------------- ------------------ 188.5/351.2 MB 6.7 MB/s eta 0:00:25
   --------------------- ------------------ 189.8/351.2 MB 6.7 MB/s eta 0:00:24
   --------------------- ------------------ 191.1/351.2 MB 6.7 MB/s eta 0:00:24
   --------------------- ------------------ 192.7/351.2 MB 6.7 MB/s eta 0:00:24
   ---------------------- ----------------- 194.0/351.2 MB 6.7 MB/s eta 0:00:24
   ---------------------- ----------------- 195.6/351.2 MB 6.7 MB/s eta 0:00:24
   ---------------------- ----------------- 196.9/351.2 MB 6.8 MB/s eta 0:00:23
   ---------------------- ----------------- 198.4/351.2 MB 6.7 MB/s eta 0:00:23
   ---------------------- ----------------- 199.8/351.2 MB 6.7 MB/s eta 0:00:23
   ---------------------- ----------------- 201.1/351.2 MB 6.7 MB/s eta 0:00:23
   ----------------------- ---------------- 202.6/351.2 MB 6.8 MB/s eta 0:00:23
   ----------------------- ---------------- 204.2/351.2 MB 6.8 MB/s eta 0:00:22
   ----------------------- ---------------- 205.8/351.2 MB 6.8 MB/s eta 0:00:22
   ----------------------- ---------------- 207.4/351.2 MB 6.8 MB/s eta 0:00:22
   ----------------------- ---------------- 208.9/351.2 MB 6.8 MB/s eta 0:00:22
   ----------------------- ---------------- 210.2/351.2 MB 6.8 MB/s eta 0:00:21
   ------------------------ --------------- 211.6/351.2 MB 6.8 MB/s eta 0:00:21
   ------------------------ --------------- 213.1/351.2 MB 6.8 MB/s eta 0:00:21
   ------------------------ --------------- 214.4/351.2 MB 6.8 MB/s eta 0:00:21
   ------------------------ --------------- 215.7/351.2 MB 6.8 MB/s eta 0:00:20
   ------------------------ --------------- 217.1/351.2 MB 6.8 MB/s eta 0:00:20
   ------------------------ --------------- 218.6/351.2 MB 6.8 MB/s eta 0:00:20
   ------------------------- -------------- 219.9/351.2 MB 6.8 MB/s eta 0:00:20
   ------------------------- -------------- 221.2/351.2 MB 6.8 MB/s eta 0:00:20
   ------------------------- -------------- 222.8/351.2 MB 6.8 MB/s eta 0:00:19
   ------------------------- -------------- 224.1/351.2 MB 6.8 MB/s eta 0:00:19
   ------------------------- -------------- 225.7/351.2 MB 6.8 MB/s eta 0:00:19
   ------------------------- -------------- 227.0/351.2 MB 6.8 MB/s eta 0:00:19
   -------------------------- ------------- 228.6/351.2 MB 6.8 MB/s eta 0:00:19
   -------------------------- ------------- 229.9/351.2 MB 6.8 MB/s eta 0:00:18
   -------------------------- ------------- 231.5/351.2 MB 6.8 MB/s eta 0:00:18
   -------------------------- ------------- 232.8/351.2 MB 6.8 MB/s eta 0:00:18
   -------------------------- ------------- 234.4/351.2 MB 6.8 MB/s eta 0:00:18
   -------------------------- ------------- 235.9/351.2 MB 6.8 MB/s eta 0:00:17
   --------------------------- ------------ 237.2/351.2 MB 6.8 MB/s eta 0:00:17
   --------------------------- ------------ 238.8/351.2 MB 6.8 MB/s eta 0:00:17
   --------------------------- ------------ 240.1/351.2 MB 6.8 MB/s eta 0:00:17
   --------------------------- ------------ 241.7/351.2 MB 6.8 MB/s eta 0:00:17
   --------------------------- ------------ 243.3/351.2 MB 6.8 MB/s eta 0:00:16
   --------------------------- ------------ 244.6/351.2 MB 6.8 MB/s eta 0:00:16
   ---------------------------- ----------- 246.2/351.2 MB 6.8 MB/s eta 0:00:16
   ---------------------------- ----------- 247.5/351.2 MB 6.8 MB/s eta 0:00:16
   ---------------------------- ----------- 248.8/351.2 MB 6.8 MB/s eta 0:00:16
   ---------------------------- ----------- 250.3/351.2 MB 6.8 MB/s eta 0:00:15
   ---------------------------- ----------- 251.7/351.2 MB 6.8 MB/s eta 0:00:15
   ---------------------------- ----------- 253.2/351.2 MB 6.8 MB/s eta 0:00:15
   ---------------------------- ----------- 254.5/351.2 MB 6.8 MB/s eta 0:00:15
   ----------------------------- ---------- 255.9/351.2 MB 6.8 MB/s eta 0:00:15
   ----------------------------- ---------- 257.4/351.2 MB 6.8 MB/s eta 0:00:14
   ----------------------------- ---------- 258.7/351.2 MB 6.8 MB/s eta 0:00:14
   ----------------------------- ---------- 260.0/351.2 MB 6.8 MB/s eta 0:00:14
   ----------------------------- ---------- 261.4/351.2 MB 6.8 MB/s eta 0:00:14
   ----------------------------- ---------- 262.7/351.2 MB 6.8 MB/s eta 0:00:14
   ------------------------------ --------- 264.0/351.2 MB 6.8 MB/s eta 0:00:13
   ------------------------------ --------- 265.3/351.2 MB 6.8 MB/s eta 0:00:13
   ------------------------------ --------- 266.6/351.2 MB 6.8 MB/s eta 0:00:13
   ------------------------------ --------- 268.2/351.2 MB 6.8 MB/s eta 0:00:13
   ------------------------------ --------- 269.5/351.2 MB 6.8 MB/s eta 0:00:13
   ------------------------------ --------- 271.1/351.2 MB 6.8 MB/s eta 0:00:12
   ------------------------------- -------- 272.4/351.2 MB 6.8 MB/s eta 0:00:12
   ------------------------------- -------- 273.7/351.2 MB 6.8 MB/s eta 0:00:12
   ------------------------------- -------- 275.3/351.2 MB 6.8 MB/s eta 0:00:12
   ------------------------------- -------- 276.6/351.2 MB 6.8 MB/s eta 0:00:11

In [43]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout, Bidirectional
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.utils import to_categorical
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler

# Convert embeddings to NumPy array
X = np.stack(new_df['bert_embedding'].values)  # BERT embeddings
y = new_df['Emotion'].values  # Emotion labels (e.g., 'happy', 'sad', etc.)

# Encode labels
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)
y_onehot = to_categorical(y_encoded)  # Convert to one-hot encoding

# Split into Train & Test sets
X_train, X_test, y_train, y_test = train_test_split(X, y_onehot, test_size=0.2, random_state=42)

# Normalize embeddings (optional but helps with LSTM performance)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Reshape input for LSTM (LSTM expects 3D input: samples, timesteps, features)
X_train = X_train.reshape((X_train.shape[0], 1, X_train.shape[1]))  # (samples, timesteps=1, features=768)
X_test = X_test.reshape((X_test.shape[0], 1, X_test.shape[1]))

In [44]:
from tensorflow.keras.layers import LayerNormalization
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout, Bidirectional
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.utils import to_categorical
# Define Improved LSTM Model
model = Sequential([
    Bidirectional(LSTM(256, return_sequences=True, input_shape=(1, X_train.shape[2]))),
    LayerNormalization(),
    Dropout(0.3),

    Bidirectional(LSTM(128, return_sequences=True)),
    LayerNormalization(),
    Dropout(0.3),

    Bidirectional(LSTM(64)),  # Final LSTM layer without return_sequences
    Dropout(0.3),

    Dense(128, activation='relu'),
    Dropout(0.3),
    Dense(y_train.shape[1], activation='softmax')  # Softmax for multi-class classification
])

# Compile with learning rate decay
optimizer = Adam(learning_rate=0.0001, decay=1e-6)
model.compile(optimizer=optimizer, loss='categorical_crossentropy', metrics=['accuracy'])


from tensorflow.keras.callbacks import ModelCheckpoint

# Save the best model based on validation accuracy
checkpoint = ModelCheckpoint("best_model.h5", monitor="val_accuracy", save_best_only=True, mode="max")

# Train the model
history = model.fit(X_train, y_train, epochs=50, batch_size=32, validation_data=(X_test, y_test), callbacks=[checkpoint])

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

C:\Users\angel\AppData\Local\Programs\Python\Python313\Lib\site-packages\keras\src\layers\rnn\rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)
C:\Users\angel\AppData\Local\Programs\Python\Python313\Lib\site-packages\keras\src\optimizers\base_optimizer.py:86: UserWarning: Argument `decay` is no longer supported and will be ignored.
  warnings.warn(

Epoch 1/50
187/188 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.1354 - loss: 2.2025

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

188/188 ━━━━━━━━━━━━━━━━━━━━ 21s 51ms/step - accuracy: 0.1728 - loss: 2.1511 - val_accuracy: 0.3364 - val_loss: 1.9978
Epoch 2/50
187/188 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.2917 - loss: 1.9851

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

188/188 ━━━━━━━━━━━━━━━━━━━━ 8s 44ms/step - accuracy: 0.3156 - loss: 1.9271 - val_accuracy: 0.4202 - val_loss: 1.6795
Epoch 3/50
188/188 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.4104 - loss: 1.6872

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

188/188 ━━━━━━━━━━━━━━━━━━━━ 8s 43ms/step - accuracy: 0.4254 - loss: 1.6234 - val_accuracy: 0.4721 - val_loss: 1.4260
Epoch 4/50
187/188 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.4848 - loss: 1.4172

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

188/188 ━━━━━━━━━━━━━━━━━━━━ 9s 46ms/step - accuracy: 0.4933 - loss: 1.3950 - val_accuracy: 0.4920 - val_loss: 1.3127
Epoch 5/50
188/188 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.5343 - loss: 1.2731

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

188/188 ━━━━━━━━━━━━━━━━━━━━ 9s 47ms/step - accuracy: 0.5398 - loss: 1.2522 - val_accuracy: 0.5213 - val_loss: 1.2934
Epoch 6/50
187/188 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.5636 - loss: 1.1792

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

188/188 ━━━━━━━━━━━━━━━━━━━━ 9s 46ms/step - accuracy: 0.5708 - loss: 1.1535 - val_accuracy: 0.5352 - val_loss: 1.2703
Epoch 7/50
187/188 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.6170 - loss: 1.0388

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

188/188 ━━━━━━━━━━━━━━━━━━━━ 8s 45ms/step - accuracy: 0.6133 - loss: 1.0562 - val_accuracy: 0.5472 - val_loss: 1.2841
Epoch 8/50
187/188 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.6429 - loss: 0.9696

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

188/188 ━━━━━━━━━━━━━━━━━━━━ 9s 46ms/step - accuracy: 0.6393 - loss: 0.9756 - val_accuracy: 0.5665 - val_loss: 1.2876
Epoch 9/50
187/188 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.6879 - loss: 0.8943

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

188/188 ━━━━━━━━━━━━━━━━━━━━ 9s 46ms/step - accuracy: 0.6765 - loss: 0.9142 - val_accuracy: 0.5758 - val_loss: 1.2928
Epoch 10/50
188/188 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.7116 - loss: 0.8141

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

188/188 ━━━━━━━━━━━━━━━━━━━━ 9s 46ms/step - accuracy: 0.7080 - loss: 0.8231 - val_accuracy: 0.5831 - val_loss: 1.3230
Epoch 11/50
187/188 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.7223 - loss: 0.7543

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

188/188 ━━━━━━━━━━━━━━━━━━━━ 8s 43ms/step - accuracy: 0.7293 - loss: 0.7496 - val_accuracy: 0.5924 - val_loss: 1.3554
Epoch 12/50
188/188 ━━━━━━━━━━━━━━━━━━━━ 9s 46ms/step - accuracy: 0.7569 - loss: 0.6937 - val_accuracy: 0.5911 - val_loss: 1.3922
Epoch 13/50
188/188 ━━━━━━━━━━━━━━━━━━━━ 9s 48ms/step - accuracy: 0.7693 - loss: 0.6379 - val_accuracy: 0.5918 - val_loss: 1.4555
Epoch 14/50
188/188 ━━━━━━━━━━━━━━━━━━━━ 9s 49ms/step - accuracy: 0.7999 - loss: 0.5855 - val_accuracy: 0.5878 - val_loss: 1.4968
Epoch 15/50
187/188 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.8142 - loss: 0.5222

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

188/188 ━━━━━━━━━━━━━━━━━━━━ 10s 51ms/step - accuracy: 0.8189 - loss: 0.5157 - val_accuracy: 0.5944 - val_loss: 1.5658
Epoch 16/50
188/188 ━━━━━━━━━━━━━━━━━━━━ 8s 44ms/step - accuracy: 0.8327 - loss: 0.4858 - val_accuracy: 0.5831 - val_loss: 1.6183
Epoch 17/50
188/188 ━━━━━━━━━━━━━━━━━━━━ 8s 44ms/step - accuracy: 0.8507 - loss: 0.4402 - val_accuracy: 0.5858 - val_loss: 1.6769
Epoch 18/50
188/188 ━━━━━━━━━━━━━━━━━━━━ 10s 51ms/step - accuracy: 0.8581 - loss: 0.4025 - val_accuracy: 0.5911 - val_loss: 1.7204
Epoch 19/50
188/188 ━━━━━━━━━━━━━━━━━━━━ 8s 45ms/step - accuracy: 0.8721 - loss: 0.3651 - val_accuracy: 0.5898 - val_loss: 1.7755
Epoch 20/50
188/188 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.8888 - loss: 0.3146

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

188/188 ━━━━━━━━━━━━━━━━━━━━ 8s 43ms/step - accuracy: 0.8828 - loss: 0.3285 - val_accuracy: 0.5971 - val_loss: 1.8396
Epoch 21/50
188/188 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.9009 - loss: 0.2874 - val_accuracy: 0.5904 - val_loss: 1.8814
Epoch 22/50
188/188 ━━━━━━━━━━━━━━━━━━━━ 8s 43ms/step - accuracy: 0.9072 - loss: 0.2705 - val_accuracy: 0.5931 - val_loss: 1.9874
Epoch 23/50
188/188 ━━━━━━━━━━━━━━━━━━━━ 8s 45ms/step - accuracy: 0.9140 - loss: 0.2519 - val_accuracy: 0.5824 - val_loss: 2.0756
Epoch 24/50
188/188 ━━━━━━━━━━━━━━━━━━━━ 8s 41ms/step - accuracy: 0.9248 - loss: 0.2219 - val_accuracy: 0.5878 - val_loss: 2.0823
Epoch 25/50
188/188 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.9288 - loss: 0.2089 - val_accuracy: 0.5904 - val_loss: 2.1499
Epoch 26/50
188/188 ━━━━━━━━━━━━━━━━━━━━ 8s 41ms/step - accuracy: 0.9391 - loss: 0.1851 - val_accuracy: 0.5924 - val_loss: 2.1998
Epoch 27/50
188/188 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.9396 - loss: 0.1838 - val_accuracy: 0.5957 - val_loss: 2.2409
Epoch 28/50
188/188 ━━━━━━━━━━━━━━━━━━━━ 8s 43ms/step - accuracy: 0.9446 - loss: 0.1747 - val_accuracy: 0.5838 - val_loss: 2.2788
Epoch 29/50
188/188 ━━━━━━━━━━━━━━━━━━━━ 9s 49ms/step - accuracy: 0.9473 - loss: 0.1619 - val_accuracy: 0.5884 - val_loss: 2.3456
Epoch 30/50
188/188 ━━━━━━━━━━━━━━━━━━━━ 9s 50ms/step - accuracy: 0.9544 - loss: 0.1414 - val_accuracy: 0.5805 - val_loss: 2.4490
Epoch 31/50
188/188 ━━━━━━━━━━━━━━━━━━━━ 9s 46ms/step - accuracy: 0.9564 - loss: 0.1272 - val_accuracy: 0.5831 - val_loss: 2.4897
Epoch 32/50
188/188 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.9583 - loss: 0.1366 - val_accuracy: 0.5798 - val_loss: 2.4501
Epoch 33/50
188/188 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.9576 - loss: 0.1308 - val_accuracy: 0.5805 - val_loss: 2.4802
Epoch 34/50
188/188 ━━━━━━━━━━━━━━━━━━━━ 8s 43ms/step - accuracy: 0.9651 - loss: 0.1112 - val_accuracy: 0.5858 - val_loss: 2.5394
Epoch 35/50
188/188 ━━━━━━━━━━━━━━━━━━━━ 8s 43ms/step - accuracy: 0.9656 - loss: 0.1083 - val_accuracy: 0.5891 - val_loss: 2.5953
Epoch 36/50
188/188 ━━━━━━━━━━━━━━━━━━━━ 8s 43ms/step - accuracy: 0.9656 - loss: 0.1065 - val_accuracy: 0.5838 - val_loss: 2.6332
Epoch 37/50
188/188 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.9624 - loss: 0.1152 - val_accuracy: 0.5811 - val_loss: 2.6420
Epoch 38/50
188/188 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.9649 - loss: 0.1073 - val_accuracy: 0.5824 - val_loss: 2.6456
Epoch 39/50
188/188 ━━━━━━━━━━━━━━━━━━━━ 8s 45ms/step - accuracy: 0.9641 - loss: 0.1088 - val_accuracy: 0.5938 - val_loss: 2.6484
Epoch 40/50
188/188 ━━━━━━━━━━━━━━━━━━━━ 8s 43ms/step - accuracy: 0.9712 - loss: 0.0950 - val_accuracy: 0.5805 - val_loss: 2.6265
Epoch 41/50
188/188 ━━━━━━━━━━━━━━━━━━━━ 8s 43ms/step - accuracy: 0.9707 - loss: 0.0945 - val_accuracy: 0.5785 - val_loss: 2.7204
Epoch 42/50
188/188 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.9736 - loss: 0.0806 - val_accuracy: 0.5871 - val_loss: 2.7369
Epoch 43/50
188/188 ━━━━━━━━━━━━━━━━━━━━ 8s 45ms/step - accuracy: 0.9741 - loss: 0.0796 - val_accuracy: 0.5878 - val_loss: 2.6796
Epoch 44/50
188/188 ━━━━━━━━━━━━━━━━━━━━ 8s 43ms/step - accuracy: 0.9747 - loss: 0.0768 - val_accuracy: 0.5911 - val_loss: 2.7590
Epoch 45/50
188/188 ━━━━━━━━━━━━━━━━━━━━ 8s 43ms/step - accuracy: 0.9759 - loss: 0.0795 - val_accuracy: 0.5904 - val_loss: 2.7322
Epoch 46/50
188/188 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.9756 - loss: 0.0745 - val_accuracy: 0.5871 - val_loss: 2.7680
Epoch 47/50
188/188 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.9807 - loss: 0.0620 - val_accuracy: 0.5864 - val_loss: 2.7990
Epoch 48/50
188/188 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.9759 - loss: 0.0791 - val_accuracy: 0.5904 - val_loss: 2.8219
Epoch 49/50
188/188 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.9775 - loss: 0.0684 - val_accuracy: 0.5878 - val_loss: 2.8279
Epoch 50/50
188/188 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.9792 - loss: 0.0654 - val_accuracy: 0.5818 - val_loss: 2.8646

In [45]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ bidirectional (Bidirectional)        │ (None, 1, 512)              │       2,099,200 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ layer_normalization                  │ (None, 1, 512)              │           1,024 │
│ (LayerNormalization)                 │                             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout (Dropout)                    │ (None, 1, 512)              │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ bidirectional_1 (Bidirectional)      │ (None, 1, 256)              │         656,384 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ layer_normalization_1                │ (None, 1, 256)              │             512 │
│ (LayerNormalization)                 │                             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_1 (Dropout)                  │ (None, 1, 256)              │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ bidirectional_2 (Bidirectional)      │ (None, 128)                 │         164,352 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_2 (Dropout)                  │ (None, 128)                 │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ (None, 128)                 │          16,512 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_3 (Dropout)                  │ (None, 128)                 │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 9)                   │           1,161 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 8,817,437 (33.64 MB)

 Trainable params: 2,939,145 (11.21 MB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 5,878,292 (22.42 MB)

In [46]:
from tensorflow.keras.callbacks import ModelCheckpoint

from tensorflow.keras.models import load_model
from sklearn.metrics import classification_report
import numpy as np

# Load the saved best model
best_model = load_model("best_model.h5")
best_model.evaluate(X_test,y_test)

# Generate predictions on the test set using the loaded best model
y_pred = best_model.predict(X_test)  # Get predicted probabilities

# Convert probabilities to class labels
y_pred_labels = np.argmax(y_pred, axis=1)  # Convert predictions to label indices
y_test_labels = np.argmax(y_test, axis=1)  # Convert one-hot encoding to label indices

# Adjust target names dynamically to match unique classes in y_test
unique_classes = np.unique(y_test_labels)  # Find unique labels in y_test
target_names = [label_encoder.classes_[i] for i in unique_classes]  # Ensure correct class names

# Print the classification report
print(classification_report(y_test_labels, y_pred_labels, target_names=target_names))

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

47/47 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.5971 - loss: 1.8396
47/47 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step
              precision    recall  f1-score   support

       anger       0.48      0.44      0.46       216
     disgust       0.53      0.55      0.54       197
        fear       0.69      0.69      0.69       228
       guilt       0.50      0.53      0.51       222
         joy       0.80      0.84      0.82       223
     sadness       0.67      0.62      0.64       202
   sentiment       0.00      0.00      0.00         1
       shame       0.50      0.50      0.50       215

    accuracy                           0.60      1504
   macro avg       0.52      0.52      0.52      1504
weighted avg       0.60      0.60      0.60      1504

C:\Users\angel\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\angel\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\angel\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [48]:
def predict_emotion(text):
    embedding = get_bert_embeddings(text).reshape(1, -1)  # Get BERT embedding
    embedding = scaler.transform(embedding)  # Normalize (same as training data)
    embedding = embedding.reshape((1, 1, embedding.shape[1]))  # Reshape for LSTM
    prediction = model.predict(embedding)
    predicted_label = np.argmax(prediction)  # Get label index
    return label_encoder.inverse_transform([predicted_label])[0]  # Convert index back to label

# Example:
print(predict_emotion("I feel so much happy!"))
print(predict_emotion("I want to be happy but it is not happening."))
print(predict_emotion("I feel like my mind is wanting for happiness and heart is pounding with burden."))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step
joy
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step
sadness
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step
sadness

In [49]:
!pip install gradio

Collecting gradio
  Downloading gradio-6.9.0-py3-none-any.whl.metadata (16 kB)
Collecting aiofiles<25.0,>=22.0 (from gradio)
  Downloading aiofiles-24.1.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: anyio<5.0,>=3.0 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from gradio) (4.8.0)
Collecting audioop-lts<1.0 (from gradio)
  Downloading audioop_lts-0.2.2-cp313-abi3-win_amd64.whl.metadata (2.0 kB)
Collecting brotli>=1.1.0 (from gradio)
  Downloading brotli-1.2.0-cp313-cp313-win_amd64.whl.metadata (6.3 kB)
Collecting fastapi<1.0,>=0.115.2 (from gradio)
  Downloading fastapi-0.135.1-py3-none-any.whl.metadata (30 kB)
Collecting ffmpy (from gradio)
  Downloading ffmpy-1.0.0-py3-none-any.whl.metadata (3.0 kB)
Collecting gradio-client==2.3.0 (from gradio)
  Downloading gradio_client-2.3.0-py3-none-any.whl.metadata (7.1 kB)
Collecting groovy~=0.1 (from gradio)
  Downloading groovy-0.1.2-py3-none-any.whl.metadata (6.1 kB)
Requirement already satisfied: httpx<1.0,>=0.24.1 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from gradio) (0.28.1)
Requirement already satisfied: huggingface-hub<2.0,>=0.33.5 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from gradio) (1.7.1)
Requirement already satisfied: jinja2<4.0 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from gradio) (3.1.5)
Requirement already satisfied: markupsafe<4.0,>=2.0 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from gradio) (3.0.2)
Requirement already satisfied: numpy<3.0,>=1.0 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from gradio) (2.2.3)
Collecting orjson~=3.0 (from gradio)
  Downloading orjson-3.11.7-cp313-cp313-win_amd64.whl.metadata (43 kB)
Requirement already satisfied: packaging in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from gradio) (24.2)
Requirement already satisfied: pandas<4.0,>=1.0 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from gradio) (2.3.3)
Requirement already satisfied: pillow<13.0,>=8.0 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from gradio) (11.1.0)
Collecting pydantic<=3.0,>=2.0 (from gradio)
  Downloading pydantic-2.12.5-py3-none-any.whl.metadata (90 kB)
Collecting pydub (from gradio)
  Downloading pydub-0.25.1-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting python-multipart>=0.0.18 (from gradio)
  Downloading python_multipart-0.0.22-py3-none-any.whl.metadata (1.8 kB)
Requirement already satisfied: pytz>=2017.2 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from gradio) (2025.2)
Requirement already satisfied: pyyaml<7.0,>=5.0 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from gradio) (6.0.2)
Collecting safehttpx<0.2.0,>=0.1.7 (from gradio)
  Downloading safehttpx-0.1.7-py3-none-any.whl.metadata (4.2 kB)
Collecting semantic-version~=2.0 (from gradio)
  Downloading semantic_version-2.10.0-py2.py3-none-any.whl.metadata (9.7 kB)
Collecting starlette<1.0,>=0.40.0 (from gradio)
  Downloading starlette-0.52.1-py3-none-any.whl.metadata (6.3 kB)
Collecting tomlkit<0.14.0,>=0.12.0 (from gradio)
  Downloading tomlkit-0.13.3-py3-none-any.whl.metadata (2.8 kB)
Requirement already satisfied: typer<1.0,>=0.12 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from gradio) (0.24.1)
Requirement already satisfied: typing-extensions~=4.0 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from gradio) (4.15.0)
Collecting uvicorn>=0.14.0 (from gradio)
  Downloading uvicorn-0.42.0-py3-none-any.whl.metadata (6.7 kB)
Requirement already satisfied: fsspec in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from gradio-client==2.3.0->gradio) (2025.9.0)
Requirement already satisfied: idna>=2.8 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from anyio<5.0,>=3.0->gradio) (3.10)
Requirement already satisfied: sniffio>=1.1 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from anyio<5.0,>=3.0->gradio) (1.3.1)
Collecting typing-inspection>=0.4.2 (from fastapi<1.0,>=0.115.2->gradio)
  Downloading typing_inspection-0.4.2-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: annotated-doc>=0.0.2 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from fastapi<1.0,>=0.115.2->gradio) (0.0.4)
Requirement already satisfied: certifi in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from httpx<1.0,>=0.24.1->gradio) (2024.12.14)
Requirement already satisfied: httpcore==1.* in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from httpx<1.0,>=0.24.1->gradio) (1.0.7)
Requirement already satisfied: h11<0.15,>=0.13 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from httpcore==1.*->httpx<1.0,>=0.24.1->gradio) (0.14.0)
Requirement already satisfied: filelock>=3.10.0 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from huggingface-hub<2.0,>=0.33.5->gradio) (3.25.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.2 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from huggingface-hub<2.0,>=0.33.5->gradio) (1.4.2)
Requirement already satisfied: tqdm>=4.42.1 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from huggingface-hub<2.0,>=0.33.5->gradio) (4.67.3)
Requirement already satisfied: python-dateutil>=2.8.2 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas<4.0,>=1.0->gradio) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas<4.0,>=1.0->gradio) (2025.2)
Collecting annotated-types>=0.6.0 (from pydantic<=3.0,>=2.0->gradio)
  Downloading annotated_types-0.7.0-py3-none-any.whl.metadata (15 kB)
Collecting pydantic-core==2.41.5 (from pydantic<=3.0,>=2.0->gradio)
  Downloading pydantic_core-2.41.5-cp313-cp313-win_amd64.whl.metadata (7.4 kB)
Requirement already satisfied: click>=8.2.1 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from typer<1.0,>=0.12->gradio) (8.2.1)
Requirement already satisfied: shellingham>=1.3.0 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from typer<1.0,>=0.12->gradio) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from typer<1.0,>=0.12->gradio) (14.3.3)
Requirement already satisfied: colorama in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from click>=8.2.1->typer<1.0,>=0.12->gradio) (0.4.6)
Requirement already satisfied: six>=1.5 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from python-dateutil>=2.8.2->pandas<4.0,>=1.0->gradio) (1.17.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from rich>=12.3.0->typer<1.0,>=0.12->gradio) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from rich>=12.3.0->typer<1.0,>=0.12->gradio) (2.19.1)
Requirement already satisfied: mdurl~=0.1 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer<1.0,>=0.12->gradio) (0.1.2)
Downloading gradio-6.9.0-py3-none-any.whl (42.9 MB)
   ---------------------------------------- 0.0/42.9 MB ? eta -:--:--
   - -------------------------------------- 1.3/42.9 MB 6.4 MB/s eta 0:00:07
   -- ------------------------------------- 2.6/42.9 MB 6.3 MB/s eta 0:00:07
   --- ------------------------------------ 3.7/42.9 MB 6.2 MB/s eta 0:00:07
   ---- ----------------------------------- 5.0/42.9 MB 6.1 MB/s eta 0:00:07
   ----- ---------------------------------- 6.3/42.9 MB 6.2 MB/s eta 0:00:06
   ------- -------------------------------- 7.6/42.9 MB 6.3 MB/s eta 0:00:06
   -------- ------------------------------- 8.9/42.9 MB 6.3 MB/s eta 0:00:06
   --------- ------------------------------ 10.5/42.9 MB 6.4 MB/s eta 0:00:06
   ---------- ----------------------------- 11.8/42.9 MB 6.4 MB/s eta 0:00:05
   ------------ --------------------------- 13.1/42.9 MB 6.4 MB/s eta 0:00:05
   ------------- -------------------------- 14.4/42.9 MB 6.5 MB/s eta 0:00:05
   -------------- ------------------------- 15.7/42.9 MB 6.4 MB/s eta 0:00:05
   --------------- ------------------------ 17.0/42.9 MB 6.5 MB/s eta 0:00:05
   ----------------- ---------------------- 18.4/42.9 MB 6.5 MB/s eta 0:00:04
   ------------------ --------------------- 19.9/42.9 MB 6.5 MB/s eta 0:00:04
   ------------------- -------------------- 21.2/42.9 MB 6.5 MB/s eta 0:00:04
   --------------------- ------------------ 22.5/42.9 MB 6.5 MB/s eta 0:00:04
   ---------------------- ----------------- 23.9/42.9 MB 6.5 MB/s eta 0:00:03
   ----------------------- ---------------- 25.2/42.9 MB 6.5 MB/s eta 0:00:03
   ------------------------ --------------- 26.5/42.9 MB 6.5 MB/s eta 0:00:03
   ------------------------- -------------- 27.8/42.9 MB 6.5 MB/s eta 0:00:03
   --------------------------- ------------ 29.1/42.9 MB 6.5 MB/s eta 0:00:03
   ---------------------------- ----------- 30.7/42.9 MB 6.5 MB/s eta 0:00:02
   ----------------------------- ---------- 32.0/42.9 MB 6.5 MB/s eta 0:00:02
   ------------------------------- -------- 33.3/42.9 MB 6.5 MB/s eta 0:00:02
   -------------------------------- ------- 34.6/42.9 MB 6.5 MB/s eta 0:00:02
   --------------------------------- ------ 36.2/42.9 MB 6.5 MB/s eta 0:00:02
   ---------------------------------- ----- 37.5/42.9 MB 6.5 MB/s eta 0:00:01
   ------------------------------------ --- 38.8/42.9 MB 6.5 MB/s eta 0:00:01
   ------------------------------------- -- 40.4/42.9 MB 6.5 MB/s eta 0:00:01
   -------------------------------------- - 41.7/42.9 MB 6.5 MB/s eta 0:00:01
   ---------------------------------------  42.7/42.9 MB 6.5 MB/s eta 0:00:01
   ---------------------------------------- 42.9/42.9 MB 6.3 MB/s  0:00:06
Downloading gradio_client-2.3.0-py3-none-any.whl (58 kB)
Downloading aiofiles-24.1.0-py3-none-any.whl (15 kB)
Downloading audioop_lts-0.2.2-cp313-abi3-win_amd64.whl (30 kB)
Downloading fastapi-0.135.1-py3-none-any.whl (116 kB)
Downloading groovy-0.1.2-py3-none-any.whl (14 kB)
Downloading orjson-3.11.7-cp313-cp313-win_amd64.whl (124 kB)
Downloading pydantic-2.12.5-py3-none-any.whl (463 kB)
Downloading pydantic_core-2.41.5-cp313-cp313-win_amd64.whl (2.0 MB)
   ---------------------------------------- 0.0/2.0 MB ? eta -:--:--
   -------------------- ------------------- 1.0/2.0 MB 6.1 MB/s eta 0:00:01
   ---------------------------------------- 2.0/2.0 MB 5.5 MB/s  0:00:00
Downloading safehttpx-0.1.7-py3-none-any.whl (9.0 kB)
Downloading semantic_version-2.10.0-py2.py3-none-any.whl (15 kB)
Downloading starlette-0.52.1-py3-none-any.whl (74 kB)
Downloading tomlkit-0.13.3-py3-none-any.whl (38 kB)
Downloading annotated_types-0.7.0-py3-none-any.whl (13 kB)
Downloading brotli-1.2.0-cp313-cp313-win_amd64.whl (369 kB)
Downloading python_multipart-0.0.22-py3-none-any.whl (24 kB)
Downloading typing_inspection-0.4.2-py3-none-any.whl (14 kB)
Downloading uvicorn-0.42.0-py3-none-any.whl (68 kB)
Downloading ffmpy-1.0.0-py3-none-any.whl (5.6 kB)
Downloading pydub-0.25.1-py2.py3-none-any.whl (32 kB)
Installing collected packages: pydub, brotli, typing-inspection, tomlkit, semantic-version, python-multipart, pydantic-core, orjson, groovy, ffmpy, audioop-lts, annotated-types, aiofiles, uvicorn, starlette, pydantic, safehttpx, fastapi, gradio-client, gradio

   ----------------------------------------  0/20 [pydub]
   ----------------------------------------  0/20 [pydub]
   ------ ---------------------------------  3/20 [tomlkit]
   ------ ---------------------------------  3/20 [tomlkit]
   ------ ---------------------------------  3/20 [tomlkit]
   ---------- -----------------------------  5/20 [python-multipart]
   ---------- -----------------------------  5/20 [python-multipart]
   ------------ ---------------------------  6/20 [pydantic-core]
   -------------- -------------------------  7/20 [orjson]
   ---------------------- ----------------- 11/20 [annotated-types]
   ------------------------ --------------- 12/20 [aiofiles]
   -------------------------- ------------- 13/20 [uvicorn]
   -------------------------- ------------- 13/20 [uvicorn]
   -------------------------- ------------- 13/20 [uvicorn]
   -------------------------- ------------- 13/20 [uvicorn]
   -------------------------- ------------- 13/20 [uvicorn]
   -------------------------- ------------- 13/20 [uvicorn]
   -------------------------- ------------- 13/20 [uvicorn]
   -------------------------- ------------- 13/20 [uvicorn]
   -------------------------- ------------- 13/20 [uvicorn]
   -------------------------- ------------- 13/20 [uvicorn]
   ---------------------------- ----------- 14/20 [starlette]
   ---------------------------- ----------- 14/20 [starlette]
   ---------------------------- ----------- 14/20 [starlette]
   ---------------------------- ----------- 14/20 [starlette]
   ---------------------------- ----------- 14/20 [starlette]
   ---------------------------- ----------- 14/20 [starlette]
   ------------------------------ --------- 15/20 [pydantic]
   ------------------------------ --------- 15/20 [pydantic]
   ------------------------------ --------- 15/20 [pydantic]
   ------------------------------ --------- 15/20 [pydantic]
   ------------------------------ --------- 15/20 [pydantic]
   ------------------------------ --------- 15/20 [pydantic]
   ------------------------------ --------- 15/20 [pydantic]
   ------------------------------ --------- 15/20 [pydantic]
   ------------------------------ --------- 15/20 [pydantic]
   ------------------------------ --------- 15/20 [pydantic]
   ------------------------------ --------- 15/20 [pydantic]
   ------------------------------ --------- 15/20 [pydantic]
   ------------------------------ --------- 15/20 [pydantic]
   ------------------------------ --------- 15/20 [pydantic]
   ------------------------------ --------- 15/20 [pydantic]
   ------------------------------ --------- 15/20 [pydantic]
   ------------------------------ --------- 15/20 [pydantic]
   -------------------------------- ------- 16/20 [safehttpx]
   ---------------------------------- ----- 17/20 [fastapi]
   ---------------------------------- ----- 17/20 [fastapi]
   ---------------------------------- ----- 17/20 [fastapi]
   ---------------------------------- ----- 17/20 [fastapi]
   ---------------------------------- ----- 17/20 [fastapi]
   ---------------------------------- ----- 17/20 [fastapi]
   ---------------------------------- ----- 17/20 [fastapi]
   ---------------------------------- ----- 17/20 [fastapi]
   ---------------------------------- ----- 17/20 [fastapi]
   ------------------------------------ --- 18/20 [gradio-client]
   -------------------------------------- - 19/20 [gradio]
   -------------------------------------- - 19/20 [gradio]
   -------------------------------------- - 19/20 [gradio]
   -------------------------------------- - 19/20 [gradio]
   -------------------------------------- - 19/20 [gradio]
   -------------------------------------- - 19/20 [gradio]
   -------------------------------------- - 19/20 [gradio]
   -------------------------------------- - 19/20 [gradio]
   -------------------------------------- - 19/20 [gradio]
   -------------------------------------- - 19/20 [gradio]
   -------------------------------------- - 19/20 [gradio]
   -------------------------------------- - 19/20 [gradio]
   -------------------------------------- - 19/20 [gradio]
   -------------------------------------- - 19/20 [gradio]
   -------------------------------------- - 19/20 [gradio]
   -------------------------------------- - 19/20 [gradio]
   -------------------------------------- - 19/20 [gradio]
   -------------------------------------- - 19/20 [gradio]
   -------------------------------------- - 19/20 [gradio]
   -------------------------------------- - 19/20 [gradio]
   -------------------------------------- - 19/20 [gradio]
   -------------------------------------- - 19/20 [gradio]
   -------------------------------------- - 19/20 [gradio]
   -------------------------------------- - 19/20 [gradio]
   -------------------------------------- - 19/20 [gradio]
   -------------------------------------- - 19/20 [gradio]
   -------------------------------------- - 19/20 [gradio]
   -------------------------------------- - 19/20 [gradio]
   -------------------------------------- - 19/20 [gradio]
   -------------------------------------- - 19/20 [gradio]
   -------------------------------------- - 19/20 [gradio]
   -------------------------------------- - 19/20 [gradio]
   -------------------------------------- - 19/20 [gradio]
   -------------------------------------- - 19/20 [gradio]
   -------------------------------------- - 19/20 [gradio]
   -------------------------------------- - 19/20 [gradio]
   -------------------------------------- - 19/20 [gradio]
   -------------------------------------- - 19/20 [gradio]
   -------------------------------------- - 19/20 [gradio]
   -------------------------------------- - 19/20 [gradio]
   -------------------------------------- - 19/20 [gradio]
   -------------------------------------- - 19/20 [gradio]
   -------------------------------------- - 19/20 [gradio]
   -------------------------------------- - 19/20 [gradio]
   -------------------------------------- - 19/20 [gradio]
   -------------------------------------- - 19/20 [gradio]
   -------------------------------------- - 19/20 [gradio]
   -------------------------------------- - 19/20 [gradio]
   -------------------------------------- - 19/20 [gradio]
   -------------------------------------- - 19/20 [gradio]
   -------------------------------------- - 19/20 [gradio]
   -------------------------------------- - 19/20 [gradio]
   ---------------------------------------- 20/20 [gradio]

Successfully installed aiofiles-24.1.0 annotated-types-0.7.0 audioop-lts-0.2.2 brotli-1.2.0 fastapi-0.135.1 ffmpy-1.0.0 gradio-6.9.0 gradio-client-2.3.0 groovy-0.1.2 orjson-3.11.7 pydantic-2.12.5 pydantic-core-2.41.5 pydub-0.25.1 python-multipart-0.0.22 safehttpx-0.1.7 semantic-version-2.10.0 starlette-0.52.1 tomlkit-0.13.3 typing-inspection-0.4.2 uvicorn-0.42.0

In [52]:
import gradio as gr
import numpy as np
from gradio.themes.base import Base
from gradio.themes.utils import colors

class MyColorfulTheme(Base):
    def __init__(self):
        super().__init__()
        self.primary_hue = colors.pink
        self.secondary_hue = colors.purple
        self.text_size = "md"
        self.radius_size = "xl"

def predict_emotion(text):
    embedding = get_bert_embeddings(text).reshape(1, -1)
    embedding = scaler.transform(embedding)
    embedding = embedding.reshape((1, 1, embedding.shape[1]))
    prediction = model.predict(embedding)
    predicted_label = np.argmax(prediction)
    return label_encoder.inverse_transform([predicted_label])[0]

iface = gr.Interface(
    fn=predict_emotion,
    inputs=gr.Textbox(
        lines=3,
        placeholder="Enter your text here...",
        label="💬 Enter Your Text",
        interactive=True
    ),
    outputs=gr.Textbox(
        lines=3,
        label="🎯 Detected Emotion"
    ),
    title="🌈 Emotion Detection",
    description="Enter a sentence and see the detected emotion!",
    theme=MyColorfulTheme(),
    flagging_mode="never"   # ✅ FIXED
)

iface.launch()

* Running on local URL:  http://127.0.0.1:7860
* To create a public link, set `share=True` in `launch()`.

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 409ms/step